/**
 * Created by cup on 9/14/16.
 */


var cities = {
    "v": "1.0",
    "cmd": "classification.cityList",
    "params": {
        "cityInfo": [{
            "cityCd": "152900",
            "cityNm": "阿拉善盟",
            "cityEnNm": "AlashanLeague",
            "firstLetter": "A",
            "validIn": "1"
        }, {
            "cityCd": "210300",
            "cityNm": "鞍山市",
            "cityEnNm": "AnshanCity",
            "firstLetter": "A",
            "validIn": "1"
        }, {
            "cityCd": "340800",
            "cityNm": "安庆市",
            "cityEnNm": "AnqingCity",
            "firstLetter": "A",
            "validIn": "1"
        }, {
            "cityCd": "410500",
            "cityNm": "安阳市",
            "cityEnNm": "AnyangCity",
            "firstLetter": "A",
            "validIn": "1"
        }, {
            "cityCd": "520400",
            "cityNm": "安顺市",
            "cityEnNm": "AnshunCity",
            "firstLetter": "A",
            "validIn": "1"
        }, {
            "cityCd": "610900",
            "cityNm": "安康市",
            "cityEnNm": "AnkangCity",
            "firstLetter": "A",
            "validIn": "1"
        }, {
            "cityCd": "652900",
            "cityNm": "阿克苏地区",
            "cityEnNm": "AksuDistrict",
            "firstLetter": "A",
            "validIn": "1"
        }, {
            "cityCd": "654300",
            "cityNm": "阿勒泰地区",
            "cityEnNm": "AletaiDistrict",
            "firstLetter": "A",
            "validIn": "1"
        }, {
            "cityCd": "659002",
            "cityNm": "阿拉尔市",
            "cityEnNm": "Ala\u0027erCity",
            "firstLetter": "A",
            "validIn": "1"
        }, {
            "cityCd": "110000",
            "cityNm": "北京市",
            "cityEnNm": "BeijingCity",
            "firstLetter": "B",
            "validIn": "1"
        }, {
            "cityCd": "130600",
            "cityNm": "保定市",
            "cityEnNm": "BaodingCity",
            "firstLetter": "B",
            "validIn": "1"
        }, {
            "cityCd": "150200",
            "cityNm": "包头市",
            "cityEnNm": "BaotouCity",
            "firstLetter": "B",
            "validIn": "1"
        }, {
            "cityCd": "150800",
            "cityNm": "巴彦淖尔市",
            "cityEnNm": "BayannaoerCity",
            "firstLetter": "B",
            "validIn": "1"
        }, {
            "cityCd": "210500",
            "cityNm": "本溪市",
            "cityEnNm": "BenxiCity",
            "firstLetter": "B",
            "validIn": "1"
        }, {
            "cityCd": "220600",
            "cityNm": "白山市",
            "cityEnNm": "BaishanCity",
            "firstLetter": "B",
            "validIn": "1"
        }, {
            "cityCd": "220800",
            "cityNm": "白城市",
            "cityEnNm": "BaichengCity",
            "firstLetter": "B",
            "validIn": "1"
        }, {
            "cityCd": "340300",
            "cityNm": "蚌埠市",
            "cityEnNm": "BengbuCity",
            "firstLetter": "B",
            "validIn": "1"
        }, {
            "cityCd": "341600",
            "cityNm": "亳州市",
            "cityEnNm": "BozhouCity",
            "firstLetter": "B",
            "validIn": "1"
        }, {
            "cityCd": "371600",
            "cityNm": "滨州市",
            "cityEnNm": "BinzhouCity",
            "firstLetter": "B",
            "validIn": "1"
        }, {
            "cityCd": "450500",
            "cityNm": "北海市",
            "cityEnNm": "BeihaiCity",
            "firstLetter": "B",
            "validIn": "1"
        }, {
            "cityCd": "451000",
            "cityNm": "百色市",
            "cityEnNm": "BaiseCity",
            "firstLetter": "B",
            "validIn": "1"
        }, {
            "cityCd": "511900",
            "cityNm": "巴中市",
            "cityEnNm": "BazhongCity",
            "firstLetter": "B",
            "validIn": "1"
        }, {
            "cityCd": "520500",
            "cityNm": "毕节市",
            "cityEnNm": "BianCity",
            "firstLetter": "B",
            "validIn": "1"
        }, {
            "cityCd": "530500",
            "cityNm": "保山市",
            "cityEnNm": "BaoshanCity",
            "firstLetter": "B",
            "validIn": "1"
        }, {
            "cityCd": "610300",
            "cityNm": "宝鸡市",
            "cityEnNm": "BaojiCity",
            "firstLetter": "B",
            "validIn": "1"
        }, {
            "cityCd": "620400",
            "cityNm": "白银市",
            "cityEnNm": "BaiyinCity",
            "firstLetter": "B",
            "validIn": "1"
        }, {
            "cityCd": "652700",
            "cityNm": "博尔塔拉",
            "cityEnNm": "BortalaMongoliaAutonomousPrefecture",
            "firstLetter": "B",
            "validIn": "1"
        }, {
            "cityCd": "652800",
            "cityNm": "巴音郭楞",
            "cityEnNm": "BayingolinMongoliaAutonomousPrefecture",
            "firstLetter": "B",
            "validIn": "1"
        }, {
            "cityCd": "510100",
            "cityNm": "成都市",
            "cityEnNm": "ChengduCity",
            "firstLetter": "C",
            "validIn": "1"
        }, {
            "cityCd": "500000",
            "cityNm": "重庆市",
            "cityEnNm": "ChongqingCity",
            "firstLetter": "C",
            "validIn": "1"
        }, {
            "cityCd": "130800",
            "cityNm": "承德市",
            "cityEnNm": "ChengdeCounty",
            "firstLetter": "C",
            "validIn": "1"
        }, {
            "cityCd": "130900",
            "cityNm": "沧州市",
            "cityEnNm": "CangzhouCity",
            "firstLetter": "C",
            "validIn": "1"
        }, {
            "cityCd": "140400",
            "cityNm": "长治市",
            "cityEnNm": "ChangzhiCity",
            "firstLetter": "C",
            "validIn": "1"
        }, {
            "cityCd": "150400",
            "cityNm": "赤峰市",
            "cityEnNm": "ChifengCity",
            "firstLetter": "C",
            "validIn": "1"
        }, {
            "cityCd": "211300",
            "cityNm": "朝阳市",
            "cityEnNm": "ChaoyangCity",
            "firstLetter": "C",
            "validIn": "1"
        }, {
            "cityCd": "220100",
            "cityNm": "长春市",
            "cityEnNm": "ChangchunCity",
            "firstLetter": "C",
            "validIn": "1"
        }, {
            "cityCd": "320400",
            "cityNm": "常州市",
            "cityEnNm": "ChangzhouCity",
            "firstLetter": "C",
            "validIn": "1"
        }, {
            "cityCd": "341100",
            "cityNm": "滁州市",
            "cityEnNm": "ChuzhouCity",
            "firstLetter": "C",
            "validIn": "1"
        }, {
            "cityCd": "341700",
            "cityNm": "池州市",
            "cityEnNm": "ChizhouCity",
            "firstLetter": "C",
            "validIn": "1"
        }, {
            "cityCd": "430100",
            "cityNm": "长沙市",
            "cityEnNm": "ChangshaCity",
            "firstLetter": "C",
            "validIn": "1"
        }, {
            "cityCd": "430700",
            "cityNm": "常德市",
            "cityEnNm": "ChangdeCity",
            "firstLetter": "C",
            "validIn": "1"
        }, {
            "cityCd": "431000",
            "cityNm": "郴州市",
            "cityEnNm": "ChenzhouCity",
            "firstLetter": "C",
            "validIn": "1"
        }, {
            "cityCd": "445100",
            "cityNm": "潮州市",
            "cityEnNm": "ChaozhouCity",
            "firstLetter": "C",
            "validIn": "1"
        }, {
            "cityCd": "451400",
            "cityNm": "崇左市",
            "cityEnNm": "ChongzuoCity",
            "firstLetter": "C",
            "validIn": "1"
        }, {
            "cityCd": "532300",
            "cityNm": "楚雄州",
            "cityEnNm": "ChuxiongYiAutonomousPrefecture",
            "firstLetter": "C",
            "validIn": "1"
        }, {
            "cityCd": "652300",
            "cityNm": "昌吉回族自治州",
            "cityEnNm": "ChangjiHuiAutonomousPrefecture",
            "firstLetter": "C",
            "validIn": "1"
        }, {
            "cityCd": "140200",
            "cityNm": "大同市",
            "cityEnNm": "DatongCity",
            "firstLetter": "D",
            "validIn": "1"
        }, {
            "cityCd": "210200",
            "cityNm": "大连市",
            "cityEnNm": "DalianCity",
            "firstLetter": "D",
            "validIn": "1"
        }, {
            "cityCd": "210600",
            "cityNm": "丹东市",
            "cityEnNm": "DandongCity",
            "firstLetter": "D",
            "validIn": "1"
        }, {
            "cityCd": "230600",
            "cityNm": "大庆市",
            "cityEnNm": "DaqingCity",
            "firstLetter": "D",
            "validIn": "1"
        }, {
            "cityCd": "232700",
            "cityNm": "大兴安岭地区",
            "cityEnNm": "Daxing\u0027anlingDistrict",
            "firstLetter": "D",
            "validIn": "1"
        }, {
            "cityCd": "370500",
            "cityNm": "东营市",
            "cityEnNm": "DongyingCity",
            "firstLetter": "D",
            "validIn": "1"
        }, {
            "cityCd": "371400",
            "cityNm": "德州市",
            "cityEnNm": "DezhouCity",
            "firstLetter": "D",
            "validIn": "1"
        }, {
            "cityCd": "441900",
            "cityNm": "东莞市",
            "cityEnNm": "DongguanCity",
            "firstLetter": "D",
            "validIn": "1"
        }, {
            "cityCd": "469003",
            "cityNm": "儋州市",
            "cityEnNm": "DanzhouCity",
            "firstLetter": "D",
            "validIn": "1"
        }, {
            "cityCd": "510600",
            "cityNm": "德阳市",
            "cityEnNm": "DeyangCity",
            "firstLetter": "D",
            "validIn": "1"
        }, {
            "cityCd": "511700",
            "cityNm": "达州市",
            "cityEnNm": "DazhouCity",
            "firstLetter": "D",
            "validIn": "1"
        }, {
            "cityCd": "532900",
            "cityNm": "大理州",
            "cityEnNm": "DaliBaiAutonomousPrefecture",
            "firstLetter": "D",
            "validIn": "1"
        }, {
            "cityCd": "533100",
            "cityNm": "德宏洲",
            "cityEnNm": "DehongDaiandJingpoAutonomousPrefecture",
            "firstLetter": "D",
            "validIn": "1"
        }, {
            "cityCd": "533400",
            "cityNm": "迪庆洲",
            "cityEnNm": "DiqingTibetanAutonomousPrefecture",
            "firstLetter": "D",
            "validIn": "1"
        }, {
            "cityCd": "150600",
            "cityNm": "鄂尔多斯市",
            "cityEnNm": "ErdosCity",
            "firstLetter": "E",
            "validIn": "1"
        }, {
            "cityCd": "420700",
            "cityNm": "鄂州市",
            "cityEnNm": "EzhouCity",
            "firstLetter": "E",
            "validIn": "1"
        }, {
            "cityCd": "422800",
            "cityNm": "恩施州",
            "cityEnNm": "EnshiTujiaandMiaoAutonomousPrefecture",
            "firstLetter": "E",
            "validIn": "1"
        }, {
            "cityCd": "350100",
            "cityNm": "福州市",
            "cityEnNm": "FuzhouCity",
            "firstLetter": "F",
            "validIn": "1"
        }, {
            "cityCd": "210400",
            "cityNm": "抚顺市",
            "cityEnNm": "FushunCity",
            "firstLetter": "F",
            "validIn": "1"
        }, {
            "cityCd": "210900",
            "cityNm": "阜新市",
            "cityEnNm": "FuxinCity",
            "firstLetter": "F",
            "validIn": "1"
        }, {
            "cityCd": "341200",
            "cityNm": "阜阳市",
            "cityEnNm": "FuyangCity",
            "firstLetter": "F",
            "validIn": "1"
        }, {
            "cityCd": "361000",
            "cityNm": "抚州市",
            "cityEnNm": "FuzhouCity",
            "firstLetter": "F",
            "validIn": "1"
        }, {
            "cityCd": "440600",
            "cityNm": "佛山市",
            "cityEnNm": "FoshanCity",
            "firstLetter": "F",
            "validIn": "1"
        }, {
            "cityCd": "440100",
            "cityNm": "广州市",
            "cityEnNm": "GuangzhouCity",
            "firstLetter": "G",
            "validIn": "1"
        }, {
            "cityCd": "360700",
            "cityNm": "赣州市",
            "cityEnNm": "GanzhouCity",
            "firstLetter": "G",
            "validIn": "1"
        }, {
            "cityCd": "450300",
            "cityNm": "桂林市",
            "cityEnNm": "GuilinCity",
            "firstLetter": "G",
            "validIn": "1"
        }, {
            "cityCd": "450800",
            "cityNm": "贵港市",
            "cityEnNm": "GuigangCity",
            "firstLetter": "G",
            "validIn": "1"
        }, {
            "cityCd": "510800",
            "cityNm": "广元市",
            "cityEnNm": "GuangyuanCity",
            "firstLetter": "G",
            "validIn": "1"
        }, {
            "cityCd": "511600",
            "cityNm": "广安市",
            "cityEnNm": "Guang\u0027anCity",
            "firstLetter": "G",
            "validIn": "1"
        }, {
            "cityCd": "513300",
            "cityNm": "甘孜洲",
            "cityEnNm": "GaiziTibetanAutonomousPrefecture",
            "firstLetter": "G",
            "validIn": "1"
        }, {
            "cityCd": "520100",
            "cityNm": "贵阳市",
            "cityEnNm": "GuiyangCity",
            "firstLetter": "G",
            "validIn": "1"
        }, {
            "cityCd": "640400",
            "cityNm": "固原市",
            "cityEnNm": "GuyuanCity",
            "firstLetter": "G",
            "validIn": "1"
        }, {
            "cityCd": "330100",
            "cityNm": "杭州市",
            "cityEnNm": "HangzhouCity",
            "firstLetter": "H",
            "validIn": "1"
        }, {
            "cityCd": "130400",
            "cityNm": "邯郸市",
            "cityEnNm": "HandanCity",
            "firstLetter": "H",
            "validIn": "1"
        }, {
            "cityCd": "131100",
            "cityNm": "衡水市",
            "cityEnNm": "HengshuiCity",
            "firstLetter": "H",
            "validIn": "1"
        }, {
            "cityCd": "150100",
            "cityNm": "呼和浩特市",
            "cityEnNm": "HohhotCity",
            "firstLetter": "H",
            "validIn": "1"
        }, {
            "cityCd": "150700",
            "cityNm": "呼伦贝尔市",
            "cityEnNm": "HulunbeirCity",
            "firstLetter": "H",
            "validIn": "1"
        }, {
            "cityCd": "211400",
            "cityNm": "葫芦岛市",
            "cityEnNm": "HuludaoCity",
            "firstLetter": "H",
            "validIn": "1"
        }, {
            "cityCd": "230100",
            "cityNm": "哈尔滨市",
            "cityEnNm": "HarbinCity",
            "firstLetter": "H",
            "validIn": "1"
        }, {
            "cityCd": "231100",
            "cityNm": "黑河市",
            "cityEnNm": "HeiheCity",
            "firstLetter": "H",
            "validIn": "1"
        }, {
            "cityCd": "320800",
            "cityNm": "淮安市",
            "cityEnNm": "HuaianCity",
            "firstLetter": "H",
            "validIn": "1"
        }, {
            "cityCd": "230400",
            "cityNm": "鹤岗市",
            "cityEnNm": "HegangCity",
            "firstLetter": "H",
            "validIn": "1"
        }, {
            "cityCd": "330500",
            "cityNm": "湖州市",
            "cityEnNm": "HuzhouCity",
            "firstLetter": "H",
            "validIn": "1"
        }, {
            "cityCd": "340100",
            "cityNm": "合肥市",
            "cityEnNm": "HefeiCity",
            "firstLetter": "H",
            "validIn": "1"
        }, {
            "cityCd": "340400",
            "cityNm": "淮南市",
            "cityEnNm": "HuainanCity",
            "firstLetter": "H",
            "validIn": "1"
        }, {
            "cityCd": "340600",
            "cityNm": "淮北市",
            "cityEnNm": "HuaibeiCity",
            "firstLetter": "H",
            "validIn": "1"
        }, {
            "cityCd": "341000",
            "cityNm": "黄山市",
            "cityEnNm": "HuangshanCity",
            "firstLetter": "H",
            "validIn": "1"
        }, {
            "cityCd": "371700",
            "cityNm": "菏泽市",
            "cityEnNm": "HezeCity",
            "firstLetter": "H",
            "validIn": "1"
        }, {
            "cityCd": "410600",
            "cityNm": "鹤壁市",
            "cityEnNm": "HebiCity",
            "firstLetter": "H",
            "validIn": "1"
        }, {
            "cityCd": "420200",
            "cityNm": "黄石市",
            "cityEnNm": "HuangshiCity",
            "firstLetter": "H",
            "validIn": "1"
        }, {
            "cityCd": "421100",
            "cityNm": "黄冈市",
            "cityEnNm": "HuanggangCity",
            "firstLetter": "H",
            "validIn": "1"
        }, {
            "cityCd": "431200",
            "cityNm": "怀化市",
            "cityEnNm": "HuaihuaCity",
            "firstLetter": "H",
            "validIn": "1"
        }, {
            "cityCd": "441300",
            "cityNm": "惠州市",
            "cityEnNm": "HuizhouCity",
            "firstLetter": "H",
            "validIn": "1"
        }, {
            "cityCd": "441600",
            "cityNm": "河源市",
            "cityEnNm": "HeyuanCity",
            "firstLetter": "H",
            "validIn": "1"
        }, {
            "cityCd": "430400",
            "cityNm": "衡阳市",
            "cityEnNm": "HengyangCity",
            "firstLetter": "H",
            "validIn": "1"
        }, {
            "cityCd": "451100",
            "cityNm": "贺州市",
            "cityEnNm": "HezhouCity",
            "firstLetter": "H",
            "validIn": "1"
        }, {
            "cityCd": "451200",
            "cityNm": "河池市",
            "cityEnNm": "HechiCity",
            "firstLetter": "H",
            "validIn": "1"
        }, {
            "cityCd": "460100",
            "cityNm": "海口市",
            "cityEnNm": "HaikouCity",
            "firstLetter": "H",
            "validIn": "1"
        }, {
            "cityCd": "532500",
            "cityNm": "红河州",
            "cityEnNm": "HongheHaniandYiAutonomousPrefecture",
            "firstLetter": "H",
            "validIn": "1"
        }, {
            "cityCd": "610700",
            "cityNm": "汉中市",
            "cityEnNm": "HanzhongCity",
            "firstLetter": "H",
            "validIn": "1"
        }, {
            "cityCd": "652200",
            "cityNm": "哈密地区",
            "cityEnNm": "HamiDistrict",
            "firstLetter": "H",
            "validIn": "1"
        }, {
            "cityCd": "140500",
            "cityNm": "晋城市",
            "cityEnNm": "JinchengCity",
            "firstLetter": "J",
            "validIn": "1"
        }, {
            "cityCd": "140700",
            "cityNm": "晋中市",
            "cityEnNm": "JinzhongCity",
            "firstLetter": "J",
            "validIn": "1"
        }, {
            "cityCd": "210700",
            "cityNm": "锦州市",
            "cityEnNm": "JinzhouCity",
            "firstLetter": "J",
            "validIn": "1"
        }, {
            "cityCd": "220200",
            "cityNm": "吉林市",
            "cityEnNm": "JilinCity",
            "firstLetter": "J",
            "validIn": "1"
        }, {
            "cityCd": "230300",
            "cityNm": "鸡西市",
            "cityEnNm": "JixiCity",
            "firstLetter": "J",
            "validIn": "1"
        }, {
            "cityCd": "230800",
            "cityNm": "佳木斯市",
            "cityEnNm": "JiamusiCity",
            "firstLetter": "J",
            "validIn": "1"
        }, {
            "cityCd": "330400",
            "cityNm": "嘉兴市",
            "cityEnNm": "JiaxingCity",
            "firstLetter": "J",
            "validIn": "1"
        }, {
            "cityCd": "330700",
            "cityNm": "金华市",
            "cityEnNm": "JinhuaCity",
            "firstLetter": "J",
            "validIn": "1"
        }, {
            "cityCd": "360200",
            "cityNm": "景德镇市",
            "cityEnNm": "JingdezhenCity",
            "firstLetter": "J",
            "validIn": "1"
        }, {
            "cityCd": "360400",
            "cityNm": "九江市",
            "cityEnNm": "JiujiangCity",
            "firstLetter": "J",
            "validIn": "1"
        }, {
            "cityCd": "360800",
            "cityNm": "吉安市",
            "cityEnNm": "Ji\u0027anCity",
            "firstLetter": "J",
            "validIn": "1"
        }, {
            "cityCd": "370100",
            "cityNm": "济南市",
            "cityEnNm": "JinanCity",
            "firstLetter": "J",
            "validIn": "1"
        }, {
            "cityCd": "370800",
            "cityNm": "济宁市",
            "cityEnNm": "JiningCity",
            "firstLetter": "J",
            "validIn": "1"
        }, {
            "cityCd": "410800",
            "cityNm": "焦作市",
            "cityEnNm": "JiaozuoCity",
            "firstLetter": "J",
            "validIn": "1"
        }, {
            "cityCd": "419000",
            "cityNm": "济源市",
            "cityEnNm": "JiyuanCity",
            "firstLetter": "J",
            "validIn": "1"
        }, {
            "cityCd": "420800",
            "cityNm": "荆门市",
            "cityEnNm": "JinmenCity",
            "firstLetter": "J",
            "validIn": "1"
        }, {
            "cityCd": "421000",
            "cityNm": "荆州市",
            "cityEnNm": "JinzhouCity",
            "firstLetter": "J",
            "validIn": "1"
        }, {
            "cityCd": "440700",
            "cityNm": "江门市",
            "cityEnNm": "JiangmenCity",
            "firstLetter": "J",
            "validIn": "1"
        }, {
            "cityCd": "445200",
            "cityNm": "揭阳市",
            "cityEnNm": "JieyangCity",
            "firstLetter": "J",
            "validIn": "1"
        }, {
            "cityCd": "410200",
            "cityNm": "开封市",
            "cityEnNm": "KaifengCity",
            "firstLetter": "K",
            "validIn": "1"
        }, {
            "cityCd": "530100",
            "cityNm": "昆明市",
            "cityEnNm": "KunmingCity",
            "firstLetter": "K",
            "validIn": "1"
        }, {
            "cityCd": "650200",
            "cityNm": "克拉玛依市",
            "cityEnNm": "KaramayCity",
            "firstLetter": "K",
            "validIn": "1"
        }, {
            "cityCd": "653100",
            "cityNm": "喀什地区",
            "cityEnNm": "KeshiDistrict",
            "firstLetter": "K",
            "validIn": "1"
        }, {
            "cityCd": "131000",
            "cityNm": "廊坊市",
            "cityEnNm": "LangfangCity",
            "firstLetter": "L",
            "validIn": "1"
        }, {
            "cityCd": "141000",
            "cityNm": "临汾市",
            "cityEnNm": "LinfenCity",
            "firstLetter": "L",
            "validIn": "1"
        }, {
            "cityCd": "141100",
            "cityNm": "吕梁市",
            "cityEnNm": "LvliangCity",
            "firstLetter": "L",
            "validIn": "1"
        }, {
            "cityCd": "211000",
            "cityNm": "辽阳市",
            "cityEnNm": "LiaoyangCity",
            "firstLetter": "L",
            "validIn": "1"
        }, {
            "cityCd": "220400",
            "cityNm": "辽源市",
            "cityEnNm": "LiaoyuanCity",
            "firstLetter": "L",
            "validIn": "1"
        }, {
            "cityCd": "320700",
            "cityNm": "连云港市",
            "cityEnNm": "LianyungangCity",
            "firstLetter": "L",
            "validIn": "1"
        }, {
            "cityCd": "331100",
            "cityNm": "丽水市",
            "cityEnNm": "LishuiCity",
            "firstLetter": "L",
            "validIn": "1"
        }, {
            "cityCd": "341500",
            "cityNm": "六安市",
            "cityEnNm": "Liu\u0027anCity",
            "firstLetter": "L",
            "validIn": "1"
        }, {
            "cityCd": "350800",
            "cityNm": "龙岩市",
            "cityEnNm": "LongyanCity",
            "firstLetter": "L",
            "validIn": "1"
        }, {
            "cityCd": "371200",
            "cityNm": "莱芜市",
            "cityEnNm": "LaiwuCity",
            "firstLetter": "L",
            "validIn": "1"
        }, {
            "cityCd": "371300",
            "cityNm": "临沂市",
            "cityEnNm": "LinyiCity",
            "firstLetter": "L",
            "validIn": "1"
        }, {
            "cityCd": "371500",
            "cityNm": "聊城市",
            "cityEnNm": "LiaochengCity",
            "firstLetter": "L",
            "validIn": "1"
        }, {
            "cityCd": "410300",
            "cityNm": "洛阳市",
            "cityEnNm": "LuoyangCity",
            "firstLetter": "L",
            "validIn": "1"
        }, {
            "cityCd": "411100",
            "cityNm": "漯河市",
            "cityEnNm": "LuoheCity",
            "firstLetter": "L",
            "validIn": "1"
        }, {
            "cityCd": "431300",
            "cityNm": "娄底市",
            "cityEnNm": "LoudiCity",
            "firstLetter": "L",
            "validIn": "1"
        }, {
            "cityCd": "450200",
            "cityNm": "柳州市",
            "cityEnNm": "LiuzhouCity",
            "firstLetter": "L",
            "validIn": "1"
        }, {
            "cityCd": "451300",
            "cityNm": "来宾市",
            "cityEnNm": "LaibinCity",
            "firstLetter": "L",
            "validIn": "1"
        }, {
            "cityCd": "510500",
            "cityNm": "泸州市",
            "cityEnNm": "LuzhouCity",
            "firstLetter": "L",
            "validIn": "1"
        }, {
            "cityCd": "511100",
            "cityNm": "乐山市",
            "cityEnNm": "LeshanCity",
            "firstLetter": "L",
            "validIn": "1"
        }, {
            "cityCd": "513400",
            "cityNm": "凉山州",
            "cityEnNm": "LiangshanYiAutonomousPrefecture",
            "firstLetter": "L",
            "validIn": "1"
        }, {
            "cityCd": "520200",
            "cityNm": "六盘水市",
            "cityEnNm": "LiupanshuiCity",
            "firstLetter": "L",
            "validIn": "1"
        }, {
            "cityCd": "530700",
            "cityNm": "丽江市",
            "cityEnNm": "LijiangCity",
            "firstLetter": "L",
            "validIn": "1"
        }, {
            "cityCd": "530900",
            "cityNm": "临沧市",
            "cityEnNm": "LincangCity",
            "firstLetter": "L",
            "validIn": "1"
        }, {
            "cityCd": "540100",
            "cityNm": "拉萨市",
            "cityEnNm": "LasaCity",
            "firstLetter": "L",
            "validIn": "1"
        }, {
            "cityCd": "620100",
            "cityNm": "兰州市",
            "cityEnNm": "LanzhouCity",
            "firstLetter": "L",
            "validIn": "1"
        }, {
            "cityCd": "231000",
            "cityNm": "牡丹江市",
            "cityEnNm": "MudanjiangCity",
            "firstLetter": "M",
            "validIn": "1"
        }, {
            "cityCd": "340500",
            "cityNm": "马鞍山市",
            "cityEnNm": "Ma\u0027anshanCity",
            "firstLetter": "M",
            "validIn": "1"
        }, {
            "cityCd": "440900",
            "cityNm": "茂名市",
            "cityEnNm": "MaomingCity",
            "firstLetter": "M",
            "validIn": "1"
        }, {
            "cityCd": "441400",
            "cityNm": "梅州市",
            "cityEnNm": "MeizhouCity",
            "firstLetter": "M",
            "validIn": "1"
        }, {
            "cityCd": "510700",
            "cityNm": "绵阳市",
            "cityEnNm": "MianyangCity",
            "firstLetter": "M",
            "validIn": "1"
        }, {
            "cityCd": "511400",
            "cityNm": "眉山市",
            "cityEnNm": "MeishanCity",
            "firstLetter": "M",
            "validIn": "1"
        }, {
            "cityCd": "320100",
            "cityNm": "南京市",
            "cityEnNm": "NanjingCity",
            "firstLetter": "N",
            "validIn": "1"
        }, {
            "cityCd": "360100",
            "cityNm": "南昌市",
            "cityEnNm": "NanchangCity",
            "firstLetter": "N",
            "validIn": "1"
        }, {
            "cityCd": "330200",
            "cityNm": "宁波市",
            "cityEnNm": "NingboCity",
            "firstLetter": "N",
            "validIn": "1"
        }, {
            "cityCd": "320600",
            "cityNm": "南通市",
            "cityEnNm": "NantongCity",
            "firstLetter": "N",
            "validIn": "1"
        }, {
            "cityCd": "350700",
            "cityNm": "南平市",
            "cityEnNm": "NanpingCity",
            "firstLetter": "N",
            "validIn": "1"
        }, {
            "cityCd": "350900",
            "cityNm": "宁德市",
            "cityEnNm": "NingdeCity",
            "firstLetter": "N",
            "validIn": "1"
        }, {
            "cityCd": "411300",
            "cityNm": "南阳市",
            "cityEnNm": "NanyangCity",
            "firstLetter": "N",
            "validIn": "1"
        }, {
            "cityCd": "450100",
            "cityNm": "南宁市",
            "cityEnNm": "NanningCity",
            "firstLetter": "N",
            "validIn": "1"
        }, {
            "cityCd": "511000",
            "cityNm": "内江市",
            "cityEnNm": "NeijiangCity",
            "firstLetter": "N",
            "validIn": "1"
        }, {
            "cityCd": "511300",
            "cityNm": "南充市",
            "cityEnNm": "NanchongCity",
            "firstLetter": "N",
            "validIn": "1"
        }, {
            "cityCd": "533300",
            "cityNm": "怒江洲",
            "cityEnNm": "NujiangLisuAutonomousPrefecture",
            "firstLetter": "N",
            "validIn": "1"
        }, {
            "cityCd": "211100",
            "cityNm": "盘锦市",
            "cityEnNm": "PanjinCity",
            "firstLetter": "P",
            "validIn": "1"
        }, {
            "cityCd": "350300",
            "cityNm": "莆田市",
            "cityEnNm": "PutianCity",
            "firstLetter": "P",
            "validIn": "1"
        }, {
            "cityCd": "360300",
            "cityNm": "萍乡市",
            "cityEnNm": "PingxiangCity",
            "firstLetter": "P",
            "validIn": "1"
        }, {
            "cityCd": "410400",
            "cityNm": "平顶山市",
            "cityEnNm": "PingdingshanCity",
            "firstLetter": "P",
            "validIn": "1"
        }, {
            "cityCd": "410900",
            "cityNm": "濮阳市",
            "cityEnNm": "PuyangCity",
            "firstLetter": "P",
            "validIn": "1"
        }, {
            "cityCd": "510400",
            "cityNm": "攀枝花市",
            "cityEnNm": "PanzhihuaCity",
            "firstLetter": "P",
            "validIn": "1"
        }, {
            "cityCd": "530800",
            "cityNm": "普洱市",
            "cityEnNm": "Pu\u0027erCity",
            "firstLetter": "P",
            "validIn": "1"
        }, {
            "cityCd": "130300",
            "cityNm": "秦皇岛市",
            "cityEnNm": "QinhuangdaoCity",
            "firstLetter": "Q",
            "validIn": "1"
        }, {
            "cityCd": "230200",
            "cityNm": "齐齐哈尔市",
            "cityEnNm": "QiqiharCity",
            "firstLetter": "Q",
            "validIn": "1"
        }, {
            "cityCd": "230900",
            "cityNm": "七台河市",
            "cityEnNm": "QitaiheCity",
            "firstLetter": "Q",
            "validIn": "1"
        }, {
            "cityCd": "330800",
            "cityNm": "衢州市",
            "cityEnNm": "QuzhouCity",
            "firstLetter": "Q",
            "validIn": "1"
        }, {
            "cityCd": "350500",
            "cityNm": "泉州市",
            "cityEnNm": "QuanzhouCity",
            "firstLetter": "Q",
            "validIn": "1"
        }, {
            "cityCd": "370200",
            "cityNm": "青岛市",
            "cityEnNm": "QingdaoCity",
            "firstLetter": "Q",
            "validIn": "1"
        }, {
            "cityCd": "450700",
            "cityNm": "钦州市",
            "cityEnNm": "QinzhouCity",
            "firstLetter": "Q",
            "validIn": "1"
        }, {
            "cityCd": "469002",
            "cityNm": "琼海市",
            "cityEnNm": "QionghaiCity",
            "firstLetter": "Q",
            "validIn": "1"
        }, {
            "cityCd": "441800",
            "cityNm": "清远市",
            "cityEnNm": "QingyuanCity",
            "firstLetter": "Q",
            "validIn": "1"
        }, {
            "cityCd": "522300",
            "cityNm": "黔西南布依族苗族自治州",
            "cityEnNm": "QianxinanBuyeiandMiaoAutonomousPrefecture",
            "firstLetter": "Q",
            "validIn": "1"
        }, {
            "cityCd": "522600",
            "cityNm": "黔东南州",
            "cityEnNm": "QiandongnanMiaoandDongAutonomousPrefecture",
            "firstLetter": "Q",
            "validIn": "1"
        }, {
            "cityCd": "522700",
            "cityNm": "黔南州",
            "cityEnNm": "QiannanBuyiandMiaoAutonomousPrefecture",
            "firstLetter": "Q",
            "validIn": "1"
        }, {
            "cityCd": "530300",
            "cityNm": "曲靖市",
            "cityEnNm": "QujinCity",
            "firstLetter": "Q",
            "validIn": "1"
        }, {
            "cityCd": "429100",
            "cityNm": "潜江市",
            "cityEnNm": "QianjiangCity",
            "firstLetter": "Q",
            "validIn": "1"
        }, {
            "cityCd": "371100",
            "cityNm": "日照市",
            "cityEnNm": "RizhaoCity",
            "firstLetter": "R",
            "validIn": "1"
        }, {
            "cityCd": "542300",
            "cityNm": "日喀则地区",
            "cityEnNm": "RikezeDistrict",
            "firstLetter": "R",
            "validIn": "1"
        }, {
            "cityCd": "310000",
            "cityNm": "上海市",
            "cityEnNm": "ShanghaiCity",
            "firstLetter": "S",
            "validIn": "1"
        }, {
            "cityCd": "210100",
            "cityNm": "沈阳市",
            "cityEnNm": "ShenyangCity",
            "firstLetter": "S",
            "validIn": "1"
        }, {
            "cityCd": "440300",
            "cityNm": "深圳市",
            "cityEnNm": "ShenzhenCity",
            "firstLetter": "S",
            "validIn": "1"
        }, {
            "cityCd": "130100",
            "cityNm": "石家庄市",
            "cityEnNm": "ShijiazhuangCity",
            "firstLetter": "S",
            "validIn": "1"
        }, {
            "cityCd": "140600",
            "cityNm": "朔州市",
            "cityEnNm": "ShuozhouCity",
            "firstLetter": "S",
            "validIn": "1"
        }, {
            "cityCd": "220300",
            "cityNm": "四平市",
            "cityEnNm": "SipingCity",
            "firstLetter": "S",
            "validIn": "1"
        }, {
            "cityCd": "220700",
            "cityNm": "松原市",
            "cityEnNm": "SongyuanCity",
            "firstLetter": "S",
            "validIn": "1"
        }, {
            "cityCd": "230500",
            "cityNm": "双鸭山市",
            "cityEnNm": "ShuangyashanCity",
            "firstLetter": "S",
            "validIn": "1"
        }, {
            "cityCd": "231200",
            "cityNm": "绥化市",
            "cityEnNm": "SuihuaCity",
            "firstLetter": "S",
            "validIn": "1"
        }, {
            "cityCd": "320500",
            "cityNm": "苏州市",
            "cityEnNm": "SuzhouCity",
            "firstLetter": "S",
            "validIn": "1"
        }, {
            "cityCd": "330600",
            "cityNm": "绍兴市",
            "cityEnNm": "ShaoxingCity",
            "firstLetter": "S",
            "validIn": "1"
        }, {
            "cityCd": "341300",
            "cityNm": "宿州市",
            "cityEnNm": "SuzhouCity",
            "firstLetter": "S",
            "validIn": "1"
        }, {
            "cityCd": "321300",
            "cityNm": "宿迁市",
            "cityEnNm": "SuqianCity",
            "firstLetter": "S",
            "validIn": "1"
        }, {
            "cityCd": "350400",
            "cityNm": "三明市",
            "cityEnNm": "SanmingCity",
            "firstLetter": "S",
            "validIn": "1"
        }, {
            "cityCd": "361100",
            "cityNm": "上饶市",
            "cityEnNm": "ShangraoCity",
            "firstLetter": "S",
            "validIn": "1"
        }, {
            "cityCd": "411200",
            "cityNm": "三门峡市",
            "cityEnNm": "SanmenxiaCity",
            "firstLetter": "S",
            "validIn": "1"
        }, {
            "cityCd": "411400",
            "cityNm": "商丘市",
            "cityEnNm": "ShangqiuCity",
            "firstLetter": "S",
            "validIn": "1"
        }, {
            "cityCd": "420300",
            "cityNm": "十堰市",
            "cityEnNm": "ShiyanCity",
            "firstLetter": "S",
            "validIn": "1"
        }, {
            "cityCd": "421300",
            "cityNm": "随州市",
            "cityEnNm": "SuizhouCity",
            "firstLetter": "S",
            "validIn": "1"
        }, {
            "cityCd": "430500",
            "cityNm": "邵阳市",
            "cityEnNm": "ShaoyangCity",
            "firstLetter": "S",
            "validIn": "1"
        }, {
            "cityCd": "440200",
            "cityNm": "韶关市",
            "cityEnNm": "ShaoguanCity",
            "firstLetter": "S",
            "validIn": "1"
        }, {
            "cityCd": "440500",
            "cityNm": "汕头市",
            "cityEnNm": "ShantouCity",
            "firstLetter": "S",
            "validIn": "1"
        }, {
            "cityCd": "441500",
            "cityNm": "汕尾市",
            "cityEnNm": "ShanweiCity",
            "firstLetter": "S",
            "validIn": "1"
        }, {
            "cityCd": "460200",
            "cityNm": "三亚市",
            "cityEnNm": "SanyaCity",
            "firstLetter": "S",
            "validIn": "1"
        }, {
            "cityCd": "510900",
            "cityNm": "遂宁市",
            "cityEnNm": "SuiningCity",
            "firstLetter": "S",
            "validIn": "1"
        }, {
            "cityCd": "611000",
            "cityNm": "商洛市",
            "cityEnNm": "ShangluoCity",
            "firstLetter": "S",
            "validIn": "1"
        }, {
            "cityCd": "640200",
            "cityNm": "石嘴山市",
            "cityEnNm": "ShizuishanCity",
            "firstLetter": "S",
            "validIn": "1"
        }, {
            "cityCd": "659001",
            "cityNm": "石河子市",
            "cityEnNm": "ShiheziCity",
            "firstLetter": "S",
            "validIn": "1"
        }, {
            "cityCd": "652100",
            "cityNm": "吐鲁番地区",
            "cityEnNm": "TurpanDistrict",
            "firstLetter": "T",
            "validIn": "1"
        }, {
            "cityCd": "120000",
            "cityNm": "天津市",
            "cityEnNm": "TianjinCity",
            "firstLetter": "T",
            "validIn": "1"
        }, {
            "cityCd": "130200",
            "cityNm": "唐山市",
            "cityEnNm": "TangshanCity",
            "firstLetter": "T",
            "validIn": "1"
        }, {
            "cityCd": "140100",
            "cityNm": "太原市",
            "cityEnNm": "TaiyuanCity",
            "firstLetter": "T",
            "validIn": "1"
        }, {
            "cityCd": "150500",
            "cityNm": "通辽市",
            "cityEnNm": "TongliaoCity",
            "firstLetter": "T",
            "validIn": "1"
        }, {
            "cityCd": "211200",
            "cityNm": "铁岭市",
            "cityEnNm": "TielingCity",
            "firstLetter": "T",
            "validIn": "1"
        }, {
            "cityCd": "220500",
            "cityNm": "通化市",
            "cityEnNm": "TonghuaCity",
            "firstLetter": "T",
            "validIn": "1"
        }, {
            "cityCd": "321200",
            "cityNm": "泰州市",
            "cityEnNm": "TaizhouCity",
            "firstLetter": "T",
            "validIn": "1"
        }, {
            "cityCd": "331000",
            "cityNm": "台州市",
            "cityEnNm": "TaizhouCity",
            "firstLetter": "T",
            "validIn": "1"
        }, {
            "cityCd": "340700",
            "cityNm": "铜陵市",
            "cityEnNm": "TonglingCity",
            "firstLetter": "T",
            "validIn": "1"
        }, {
            "cityCd": "370900",
            "cityNm": "泰安市",
            "cityEnNm": "TaianCity",
            "firstLetter": "T",
            "validIn": "1"
        }, {
            "cityCd": "429006",
            "cityNm": "天门市",
            "cityEnNm": "TianmenCity",
            "firstLetter": "T",
            "validIn": "1"
        }, {
            "cityCd": "520600",
            "cityNm": "铜仁市",
            "cityEnNm": "TonganCity",
            "firstLetter": "T",
            "validIn": "1"
        }, {
            "cityCd": "620500",
            "cityNm": "天水市",
            "cityEnNm": "TianshuiCity",
            "firstLetter": "T",
            "validIn": "1"
        }, {
            "cityCd": "654200",
            "cityNm": "塔城地区",
            "cityEnNm": "TachengDistrict",
            "firstLetter": "T",
            "validIn": "1"
        }, {
            "cityCd": "659003",
            "cityNm": "图木舒克市",
            "cityEnNm": "TumushukeCity",
            "firstLetter": "T",
            "validIn": "1"
        }, {
            "cityCd": "420100",
            "cityNm": "武汉市",
            "cityEnNm": "WuhanCity",
            "firstLetter": "W",
            "validIn": "1"
        }, {
            "cityCd": "150300",
            "cityNm": "乌海市",
            "cityEnNm": "WuhaiCity",
            "firstLetter": "W",
            "validIn": "1"
        }, {
            "cityCd": "150900",
            "cityNm": "乌兰察布市",
            "cityEnNm": "WulanchabuCity",
            "firstLetter": "W",
            "validIn": "1"
        }, {
            "cityCd": "320200",
            "cityNm": "无锡市",
            "cityEnNm": "WuxiCity",
            "firstLetter": "W",
            "validIn": "1"
        }, {
            "cityCd": "330300",
            "cityNm": "温州市",
            "cityEnNm": "WenzhouCity",
            "firstLetter": "W",
            "validIn": "1"
        }, {
            "cityCd": "340200",
            "cityNm": "芜湖市",
            "cityEnNm": "WuhuCity",
            "firstLetter": "W",
            "validIn": "1"
        }, {
            "cityCd": "370700",
            "cityNm": "潍坊市",
            "cityEnNm": "WeifangCity",
            "firstLetter": "W",
            "validIn": "1"
        }, {
            "cityCd": "371000",
            "cityNm": "威海市",
            "cityEnNm": "WeihaiCity",
            "firstLetter": "W",
            "validIn": "1"
        }, {
            "cityCd": "450400",
            "cityNm": "梧州市",
            "cityEnNm": "WuzhouCity",
            "firstLetter": "W",
            "validIn": "1"
        }, {
            "cityCd": "532600",
            "cityNm": "文山州",
            "cityEnNm": "WenshanZhuangandMiaoAutonomousPrefecture",
            "firstLetter": "W",
            "validIn": "1"
        }, {
            "cityCd": "610500",
            "cityNm": "渭南市",
            "cityEnNm": "WeinanCity",
            "firstLetter": "W",
            "validIn": "1"
        }, {
            "cityCd": "640300",
            "cityNm": "吴忠市",
            "cityEnNm": "WuzhongCity",
            "firstLetter": "W",
            "validIn": "1"
        }, {
            "cityCd": "650100",
            "cityNm": "乌鲁木齐市",
            "cityEnNm": "WulumuqiCity",
            "firstLetter": "W",
            "validIn": "1"
        }, {
            "cityCd": "659004",
            "cityNm": "五家渠市",
            "cityEnNm": "WujiaquCity",
            "firstLetter": "W",
            "validIn": "1"
        }, {
            "cityCd": "350200",
            "cityNm": "厦门市",
            "cityEnNm": "XiamenCity",
            "firstLetter": "X",
            "validIn": "1"
        }, {
            "cityCd": "130500",
            "cityNm": "邢台市",
            "cityEnNm": "XingtaiCity",
            "firstLetter": "X",
            "validIn": "1"
        }, {
            "cityCd": "140900",
            "cityNm": "忻州市",
            "cityEnNm": "XinzhouCity",
            "firstLetter": "X",
            "validIn": "1"
        }, {
            "cityCd": "152200",
            "cityNm": "兴安盟",
            "cityEnNm": "Xing\u0027anLeague",
            "firstLetter": "X",
            "validIn": "1"
        }, {
            "cityCd": "152500",
            "cityNm": "锡林郭勒盟",
            "cityEnNm": "XilinguoleLeague",
            "firstLetter": "X",
            "validIn": "1"
        }, {
            "cityCd": "320300",
            "cityNm": "徐州市",
            "cityEnNm": "XuzhouDistrict",
            "firstLetter": "X",
            "validIn": "1"
        }, {
            "cityCd": "341800",
            "cityNm": "宣城市",
            "cityEnNm": "XuanchengCity",
            "firstLetter": "X",
            "validIn": "1"
        }, {
            "cityCd": "360500",
            "cityNm": "新余市",
            "cityEnNm": "XinyuCity",
            "firstLetter": "X",
            "validIn": "1"
        }, {
            "cityCd": "410700",
            "cityNm": "新乡市",
            "cityEnNm": "XinxiangCity",
            "firstLetter": "X",
            "validIn": "1"
        }, {
            "cityCd": "411000",
            "cityNm": "许昌市",
            "cityEnNm": "XuchangCity",
            "firstLetter": "X",
            "validIn": "1"
        }, {
            "cityCd": "411500",
            "cityNm": "信阳市",
            "cityEnNm": "XinyangCity",
            "firstLetter": "X",
            "validIn": "1"
        }, {
            "cityCd": "420600",
            "cityNm": "襄阳市",
            "cityEnNm": "XiangyangCity",
            "firstLetter": "X",
            "validIn": "1"
        }, {
            "cityCd": "420900",
            "cityNm": "孝感市",
            "cityEnNm": "XiaoganCity",
            "firstLetter": "X",
            "validIn": "1"
        }, {
            "cityCd": "421200",
            "cityNm": "咸宁市",
            "cityEnNm": "XianningCity",
            "firstLetter": "X",
            "validIn": "1"
        }, {
            "cityCd": "429000",
            "cityNm": "仙桃市",
            "cityEnNm": "XiantaoCity",
            "firstLetter": "X",
            "validIn": "1"
        }, {
            "cityCd": "430300",
            "cityNm": "湘潭市",
            "cityEnNm": "XiangtanCity",
            "firstLetter": "X",
            "validIn": "1"
        }, {
            "cityCd": "433100",
            "cityNm": "湘西州",
            "cityEnNm": "XiangxiTujiaandMiaoAutonomousPrefecture",
            "firstLetter": "X",
            "validIn": "1"
        }, {
            "cityCd": "532800",
            "cityNm": "西双版纳",
            "cityEnNm": "XishuangbannaDaiAutonomousPrefecture",
            "firstLetter": "X",
            "validIn": "1"
        }, {
            "cityCd": "610100",
            "cityNm": "西安市",
            "cityEnNm": "Xi\u0027anCity",
            "firstLetter": "X",
            "validIn": "1"
        }, {
            "cityCd": "610400",
            "cityNm": "咸阳市",
            "cityEnNm": "XianyangCity",
            "firstLetter": "X",
            "validIn": "1"
        }, {
            "cityCd": "630100",
            "cityNm": "西宁市",
            "cityEnNm": "XiningCity",
            "firstLetter": "X",
            "validIn": "1"
        }, {
            "cityCd": "140300",
            "cityNm": "阳泉市",
            "cityEnNm": "YangquanCity",
            "firstLetter": "Y",
            "validIn": "1"
        }, {
            "cityCd": "140800",
            "cityNm": "运城市",
            "cityEnNm": "YunchengCity",
            "firstLetter": "Y",
            "validIn": "1"
        }, {
            "cityCd": "210800",
            "cityNm": "营口市",
            "cityEnNm": "YingkouCity",
            "firstLetter": "Y",
            "validIn": "1"
        }, {
            "cityCd": "222400",
            "cityNm": "延边州",
            "cityEnNm": "YanbianKoreanAutonomousPrefecture",
            "firstLetter": "Y",
            "validIn": "1"
        }, {
            "cityCd": "230700",
            "cityNm": "伊春市",
            "cityEnNm": "YichunCity",
            "firstLetter": "Y",
            "validIn": "1"
        }, {
            "cityCd": "320900",
            "cityNm": "盐城市",
            "cityEnNm": "YanchengCity",
            "firstLetter": "Y",
            "validIn": "1"
        }, {
            "cityCd": "321000",
            "cityNm": "扬州市",
            "cityEnNm": "YangzhouCity",
            "firstLetter": "Y",
            "validIn": "1"
        }, {
            "cityCd": "360600",
            "cityNm": "鹰潭市",
            "cityEnNm": "YingtanCity",
            "firstLetter": "Y",
            "validIn": "1"
        }, {
            "cityCd": "360900",
            "cityNm": "宜春市",
            "cityEnNm": "YichunCity",
            "firstLetter": "Y",
            "validIn": "1"
        }, {
            "cityCd": "370600",
            "cityNm": "烟台市",
            "cityEnNm": "YantaiCity",
            "firstLetter": "Y",
            "validIn": "1"
        }, {
            "cityCd": "420500",
            "cityNm": "宜昌市",
            "cityEnNm": "YichangCity",
            "firstLetter": "Y",
            "validIn": "1"
        }, {
            "cityCd": "430600",
            "cityNm": "岳阳市",
            "cityEnNm": "YueyangCity",
            "firstLetter": "Y",
            "validIn": "1"
        }, {
            "cityCd": "430900",
            "cityNm": "益阳市",
            "cityEnNm": "YiyangDistrict",
            "firstLetter": "Y",
            "validIn": "1"
        }, {
            "cityCd": "431100",
            "cityNm": "永州市",
            "cityEnNm": "YongzhouCity",
            "firstLetter": "Y",
            "validIn": "1"
        }, {
            "cityCd": "441700",
            "cityNm": "阳江市",
            "cityEnNm": "YangjiangCity",
            "firstLetter": "Y",
            "validIn": "1"
        }, {
            "cityCd": "445300",
            "cityNm": "云浮市",
            "cityEnNm": "YunfuCity",
            "firstLetter": "Y",
            "validIn": "1"
        }, {
            "cityCd": "450900",
            "cityNm": "玉林市",
            "cityEnNm": "YulinCity",
            "firstLetter": "Y",
            "validIn": "1"
        }, {
            "cityCd": "511500",
            "cityNm": "宜宾市",
            "cityEnNm": "YibinCity",
            "firstLetter": "Y",
            "validIn": "1"
        }, {
            "cityCd": "511800",
            "cityNm": "雅安市",
            "cityEnNm": "Ya\u0027anCity",
            "firstLetter": "Y",
            "validIn": "1"
        }, {
            "cityCd": "530400",
            "cityNm": "玉溪市",
            "cityEnNm": "YuxiCity",
            "firstLetter": "Y",
            "validIn": "1"
        }, {
            "cityCd": "610600",
            "cityNm": "延安市",
            "cityEnNm": "Yan\u0027anCity",
            "firstLetter": "Y",
            "validIn": "1"
        }, {
            "cityCd": "610800",
            "cityNm": "榆林市",
            "cityEnNm": "YulinCity",
            "firstLetter": "Y",
            "validIn": "1"
        }, {
            "cityCd": "640100",
            "cityNm": "银川市",
            "cityEnNm": "YinchuanCity",
            "firstLetter": "Y",
            "validIn": "1"
        }, {
            "cityCd": "654000",
            "cityNm": "伊犁",
            "cityEnNm": "YliKazakhAutonomousPrefecture",
            "firstLetter": "Y",
            "validIn": "1"
        }, {
            "cityCd": "130700",
            "cityNm": "张家口市",
            "cityEnNm": "ZhangjiakouCity",
            "firstLetter": "Z",
            "validIn": "1"
        }, {
            "cityCd": "321100",
            "cityNm": "镇江市",
            "cityEnNm": "ZhenjiangCity",
            "firstLetter": "Z",
            "validIn": "1"
        }, {
            "cityCd": "330900",
            "cityNm": "舟山市",
            "cityEnNm": "ZhoushanCity",
            "firstLetter": "Z",
            "validIn": "1"
        }, {
            "cityCd": "350600",
            "cityNm": "漳州市",
            "cityEnNm": "ZhangzhouCity",
            "firstLetter": "Z",
            "validIn": "1"
        }, {
            "cityCd": "370300",
            "cityNm": "淄博市",
            "cityEnNm": "ZiboCity",
            "firstLetter": "Z",
            "validIn": "1"
        }, {
            "cityCd": "370400",
            "cityNm": "枣庄市",
            "cityEnNm": "ZaozhuangCity",
            "firstLetter": "Z",
            "validIn": "1"
        }, {
            "cityCd": "410100",
            "cityNm": "郑州市",
            "cityEnNm": "ZhengzhouDistrict",
            "firstLetter": "Z",
            "validIn": "1"
        }, {
            "cityCd": "411600",
            "cityNm": "周口市",
            "cityEnNm": "ZhoukouCity",
            "firstLetter": "Z",
            "validIn": "1"
        }, {
            "cityCd": "411700",
            "cityNm": "驻马店市",
            "cityEnNm": "ZhumadianCity",
            "firstLetter": "Z",
            "validIn": "1"
        }, {
            "cityCd": "430200",
            "cityNm": "株洲市",
            "cityEnNm": "ZhuzhouCity",
            "firstLetter": "Z",
            "validIn": "1"
        }, {
            "cityCd": "430800",
            "cityNm": "张家界市",
            "cityEnNm": "ZhangjiajieCity",
            "firstLetter": "Z",
            "validIn": "1"
        }, {
            "cityCd": "440400",
            "cityNm": "珠海市",
            "cityEnNm": "ZhuhaiCity",
            "firstLetter": "Z",
            "validIn": "1"
        }, {
            "cityCd": "440800",
            "cityNm": "湛江市",
            "cityEnNm": "ZhanjiangCity",
            "firstLetter": "Z",
            "validIn": "1"
        }, {
            "cityCd": "441200",
            "cityNm": "肇庆市",
            "cityEnNm": "ZhaoqingCity",
            "firstLetter": "Z",
            "validIn": "1"
        }, {
            "cityCd": "442000",
            "cityNm": "中山市",
            "cityEnNm": "ZhongshanCity",
            "firstLetter": "Z",
            "validIn": "1"
        }, {
            "cityCd": "510300",
            "cityNm": "自贡市",
            "cityEnNm": "ZigongCity",
            "firstLetter": "Z",
            "validIn": "1"
        }, {
            "cityCd": "512000",
            "cityNm": "资阳市",
            "cityEnNm": "ZiyangCity",
            "firstLetter": "Z",
            "validIn": "1"
        }, {
            "cityCd": "520300",
            "cityNm": "遵义市",
            "cityEnNm": "ZunyiCity",
            "firstLetter": "Z",
            "validIn": "1"
        }, {
            "cityCd": "530600",
            "cityNm": "昭通市",
            "cityEnNm": "ZhaotongCity",
            "firstLetter": "Z",
            "validIn": "1"
        }, {
            "cityCd": "620700",
            "cityNm": "张掖市",
            "cityEnNm": "ZhangyeCity",
            "firstLetter": "Z",
            "validIn": "1"
        }, {"cityCd": "640500", "cityNm": "中卫市", "cityEnNm": "ZhongweiCity", "firstLetter": "Z", "validIn": "1"}],
        "hotCityData": [{
            "cityCd": "110000",
            "cityNm": "北京市",
            "cityEnNm": "BeijingCity",
            "firstLetter": "B",
            "validIn": "1"
        }, {
            "cityCd": "310000",
            "cityNm": "上海市",
            "cityEnNm": "ShanghaiCity",
            "firstLetter": "S",
            "validIn": "1"
        }, {
            "cityCd": "440100",
            "cityNm": "广州市",
            "cityEnNm": "GuangzhouCity",
            "firstLetter": "G",
            "validIn": "1"
        }, {
            "cityCd": "330100",
            "cityNm": "杭州市",
            "cityEnNm": "HangzhouCity",
            "firstLetter": "H",
            "validIn": "1"
        }, {
            "cityCd": "320100",
            "cityNm": "南京市",
            "cityEnNm": "NanjingCity",
            "firstLetter": "N",
            "validIn": "1"
        }, {
            "cityCd": "510100",
            "cityNm": "成都市",
            "cityEnNm": "ChengduCity",
            "firstLetter": "C",
            "validIn": "1"
        }, {
            "cityCd": "360100",
            "cityNm": "南昌市",
            "cityEnNm": "NanchangCity",
            "firstLetter": "N",
            "validIn": "1"
        }, {
            "cityCd": "420100",
            "cityNm": "武汉市",
            "cityEnNm": "WuhanCity",
            "firstLetter": "W",
            "validIn": "1"
        }, {
            "cityCd": "210100",
            "cityNm": "沈阳市",
            "cityEnNm": "ShenyangCity",
            "firstLetter": "S",
            "validIn": "1"
        }, {
            "cityCd": "350100",
            "cityNm": "福州市",
            "cityEnNm": "FuzhouCity",
            "firstLetter": "F",
            "validIn": "1"
        }, {
            "cityCd": "330200",
            "cityNm": "宁波市",
            "cityEnNm": "NingboCity",
            "firstLetter": "N",
            "validIn": "1"
        }, {
            "cityCd": "500000",
            "cityNm": "重庆市",
            "cityEnNm": "ChongqingCity",
            "firstLetter": "C",
            "validIn": "1"
        }, {
            "cityCd": "440300",
            "cityNm": "深圳市",
            "cityEnNm": "ShenzhenCity",
            "firstLetter": "S",
            "validIn": "1"
        }, {
            "cityCd": "350200",
            "cityNm": "厦门市",
            "cityEnNm": "XiamenCity",
            "firstLetter": "X",
            "validIn": "1"
        }, {"cityCd": "652100", "cityNm": "吐鲁番地区", "cityEnNm": "TurpanDistrict", "firstLetter": "T", "validIn": "1"}]
    },
    "msg": "",
    "resp": "00"
}